In [9]:
from sklearn import svm
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
pd.options.mode.chained_assignment = None
import warnings
warnings.filterwarnings('ignore')

#data = pd.read_csv("fifth-run/feats_version_5_1_acc.csv",  usecols = ['acc_x_autoregyw_1', 'acc_y_autoregyw_1', 'acc_y_entropy', 'acc_x_entropy', 'acc_z_autoregyw_1', 'acc_z_entropy', 'acc_z_skewness_t', 'acc_y_corecoef', 'acc_x_corecoef', 'acc_x_skewness_t', 'acc_y_skewness_t', 'acc_y_autoregburg_4', 'acc_x_top3', 'acc_x_kurtosis_t', 'acc_y_kurtosis_t', 'acc_z_corecoef', 'acc_z_crossco', 'acc_x_autoregburg_4', 'acc_z_autoregburg_4', 'acc_y_top3', 'acc_x_crossco', 'acc_z_mean', 'acc_y_mean', 'acc_x_autoregburg_1', 'acc_y_one_quarter', 'acc_y_stdev', 'acc_z_stdev', 'acc_y_enwacto_5',  'acc_y_enwacto_6', 'acc_x_enwacto_5', 'acc_y_enwacto_7', 'acc_z_enwacto_6', 'acc_y_enwacto_4', 'acc_z_enwacto_5', 'acc_y_enwacto_2', 'acc_x_stdev', 'acc_z_enwacto_7', 'acc_x_enwacto_6', 'name','activity'])
data = pd.read_csv('fifth-run/feats_version_5_22_acc.csv')
data = data[~data["activity"].str.contains("jogging")]
data["activity"] = data["activity"].replace(["sitting", "lying"], "resting")

result = data[data["name"].str.contains("kuba")]

result_train = data[data["name"].str.contains("kuba") == False]


result_train.drop('name', axis=1, inplace=True)
result.drop('name', axis=1, inplace=True)

X_train = result_train.iloc[:, :-1].values
y_train = result_train.iloc[:, -1].values

X_test = result.iloc[:, :-1].values
y_test = result.iloc[:, -1].values


import joblib
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Przykładowe dane
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Tworzenie i trenowanie modelu SVM
classifier = svm.SVC(kernel='linear', C=0.001, max_iter=50000)
classifier.fit(X_train, y_train)

# Predykcja na danych testowych
y_pred = classifier.predict(X_test)

# Ocen dokładność modelu
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Zapisz model do pliku
joblib.dump(classifier, 'modelsvm.h5')



#from xgboost import XGBClassifier
#classifier = svm.SVC(kernel='linear', C = 0.001, max_iter = 50000 )
#classifier = XGBClassifier()
#classifier.fit(X_train, y_train)
#y_pred = classifier.predict(X_test)
#print(f"accuracy:",accuracy_score(y_test, y_pred))

#wagi na poddstawie liczebności
#print(classification_report(y_test, y_pred), "\n\n\n")

Accuracy: 0.7707979626485568


['modelsvm.h5']

In [7]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import numpy as np
class_mapping = {
    0: "downstairs",  # Replace with your actual class name or label
    1: "resting",
    2: "squats",
    3: "standing",
    4: "upstairs",
    5:  "walking" }

listt =[]
for key in class_mapping.values():
    listt.append(key)
print("Classification Report:\n", classification_report(y_test, y_pred))

# Generate and print confusion matrix
confusion_mtx = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mtx)

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_mtx, annot=True, fmt='d', cmap='Blues', xticklabels=listt, yticklabels=listt)
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix from SVM Model')
plt.show()

Classification Report:
               precision    recall  f1-score   support

  downstairs       0.55      0.83      0.66        35
     resting       1.00      0.72      0.84       209
      squats       0.58      0.45      0.51        71
    standing       0.67      1.00      0.80        71
    upstairs       0.09      0.07      0.08        27
     walking       0.84      0.96      0.89       176

    accuracy                           0.77       589
   macro avg       0.62      0.67      0.63       589
weighted avg       0.79      0.77      0.77       589

Confusion Matrix:
 [[ 29   0   0   0   1   5]
 [  0 151  23  35   0   0]
 [  0   0  32   0  19  20]
 [  0   0   0  71   0   0]
 [ 17   0   0   0   2   8]
 [  7   0   0   0   0 169]]


NameError: name 'plt' is not defined

In [6]:
class_labels = np.unique(y_test)  # Get unique class labels

class_report = classification_report(y_test, y_pred, target_names=listt, output_dict=True)
class_report_str = "Classification Report:\n"
# Add header
class_report_str += " " * 10 + " " * 15 + "Precision" + " " * 8 + "Recall" + " " * 11 + "F1-Score\n"
class_report_str += "-" * 70 + "\n"

# Add individual class metrics
for label in class_labels:
    class_report_str += f"{label:10}{' ' * 5}"
    class_report_str += f"{class_report[label]['precision']:15.2f}"
    class_report_str += f"{class_report[label]['recall']:15.2f}"
    class_report_str += f"{class_report[label]['f1-score']:15.2f}\n"

# Display the modified classification report
print(class_report_str)

Classification Report:
                         Precision        Recall           F1-Score
----------------------------------------------------------------------
downstairs                0.55           0.83           0.66
resting                   1.00           0.72           0.84
squats                    0.58           0.45           0.51
standing                  0.67           1.00           0.80
upstairs                  0.09           0.07           0.08
walking                   0.84           0.96           0.89



## XGBOOST


In [34]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()

labels_train1 = encoder.fit_transform(y_train)
#print(labels_train)

labels_test1 = encoder.transform(y_test)

classifier = XGBClassifier()
classifier.fit(X_train, labels_train1)
y_pred = classifier.predict(X_test)
print(f"Accuracy:",accuracy_score(labels_test1, y_pred))



Accuracy: 0.6926994906621392


NameError: name 'multilabel_confusion_matrix' is not defined

In [39]:
from xgboost import XGBClassifier
from sklearn.metrics import multilabel_confusion_matrix, classification_report
# Predict on the test set

classifier = XGBClassifier()
classifier.fit(X_train, labels_train1)

# Predict on the test set
y_pred = classifier.predict(X_test)
# Calculate multilabel confusion matrix
conf_matrix = multilabel_confusion_matrix(labels_test1, y_pred)

# Display confusion matrix and classification report
#for i, conf in enumerate(conf_matrix):
#    print(f"Confusion Matrix for Label {i}:\n", conf)
#    print(f"Classification Report for Label {i}:\n", classification_report(y_test[:, i], y_pred[:, i]))

# Overall metrics
print("Overall Classification Report:\n", classification_report(labels_test1, y_pred))


Overall Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.97      0.71        35
           1       1.00      0.96      0.98       209
           2       1.00      0.44      0.61        71
           3       1.00      0.59      0.74        71
           4       1.00      0.19      0.31        27
           5       0.96      0.62      0.75       176

   micro avg       0.93      0.71      0.81       589
   macro avg       0.92      0.63      0.68       589
weighted avg       0.96      0.71      0.79       589
 samples avg       0.70      0.71      0.71       589



ValueError: multilabel-indicator is not supported